+ testLgsmUpdate

diff --git a/commands/lgsm-init b/commands/lgsm-init
--- a/commands/lgsm-init
+++ b/commands/lgsm-init
@@ -3,5 +3,15 @@
 set -o errexit
 set -o nounset
 
+# is gameserver already installed ?
+# if linuxgsm.sh is changed = update -> remove lgsm folder
+# if linuxgsm.sh isn't there this will also fail -> forced lgsm download
+if ! echo "$(sha256sum "$LGSM_SCRIPTS/linuxgsm.sh" | grep -Eo '^[^ ]*')  linuxgsm.sh" | sha256sum -c > /dev/null 2>&1; then
+    echo "[lgsm-init] force uninstall lgsm, either linuxgsm changed or file to determine installed version is removed"
+    rm -rf "lgsm" || true
+fi
+# remove gameserver executable to not install 2nd one 
+rm "$LGSM_GAMESERVER" > /dev/null 2>&1 || true
+
 gosu "$USER_NAME" cp -f "$LGSM_SCRIPTS/linuxgsm.sh" .
 gosu "$USER_NAME" ./linuxgsm.sh "$LGSM_GAMESERVER"
